Perfume_Layte/Areas/Admin/Controllers/CateguryController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Perfume_Layte.Permition;
using PerfumeLayte.Application.Interfaces.IFacadPattern;
using PerfumeLayte.Application.Services.Product.Commands.AddNewCategury;
using PerfumeLayte.Application.Services.Product.Querises.GetCateguryList;

namespace Perfume_Layte.Areas.Admin.Controllers
{
    [PermisionChecker(true)]
    [Authorize]
    [Area("Admin")]
    public class CateguryController : Controller
    {
        private readonly IFacadProduct _IFacadProduct;

        public CateguryController(IFacadProduct IFacadProduct)
        {
            _IFacadProduct = IFacadProduct;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var ListData = await _IFacadProduct.IListCategury.Execute();
            return View(ListData);
        }



        [HttpGet]
        public async Task<IActionResult> AddCategury(int ID)
        {
                ViewData["ParentCategury"] = ID;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddCategury(string ID, CateguryAddDto CateguryDto)
        {
            var ParendID = Convert.ToInt32(ID);
            var res = await _IFacadProduct.IAddCateguryServises.AddCategury(ParendID, CateguryDto);
            return View();
        }
    }
}

Perfume_Layte/Areas/Admin/Views/Categury/AddCategury.cshtml
@using PerfumeLayte.Application.Services.Product.Commands.AddNewCategury;
@model CateguryAddDto;
@{
    ViewData["Title"] = "افزودن گروه ";
}
<form asp-action="AddCategury" asp-controller="Categury" method="post" class="p-5">
    <input name="ID" value="@ViewData["ParentCategury"]" hidden class="form-control" />
    @ViewData["ParentCategury"]
    <input asp-for="@Model.CateguryName" type="text" class="form-control" />


    <button type="submit">ذخیره</button>

</form>

Perfume_Layte/Areas/Admin/Views/Categury/Index.cshtml
@using PerfumeLayte.Application.Services.Product.Querises.GetCateguryList;
@model List<CateguryDto>
@{
    ViewData["Title"] = "افزودن گروه ";
}
<div class="card-body">
    <div class="table-responsive">
        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row">
                <div class="col-sm-12">
                    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                        <thead>
                            <tr role="row">
                                <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 107px;">نام</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 164px;">زیر گروه</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 75px;">عملیات</th>
                        </thead>
                        <tbody>
                            @if(Model.Any())
                            {
                                @foreach(var item in Model.Where(c => c.ParentCategoryId == null))
                                {
                                    <tr class="odd">
                                        <td class="sorting_1">@item.Name</td>
                                        <td>
                                            @foreach(var items in Model.Where(c => c.ParentCategoryId == item.CateguryDtoID))
                                            {
                                                <p>@items.Name</p>
                                            }
                                        </td>
                                        <td>
                                            <button>ویرایش</button>
                                            <button>حذف</button>
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div>
        </div>
    </div>
</div>